#!/bin/bash
##############################################################################
# File: postinst
# Author: Nate Lao (nlao1@jh.edu)
# Created On: 3/30/2020
# Description:
#       Debian post installation script.
##############################################################################

FRONTEND_DIR='/opt/clueless/src/frontend'
SERVERSIDE_DIR='/opt/clueless/src/serverside'
BIN_DIR='/opt/clueless/bin'
ETC_DIR='/opt/clueless/etc'
USR_BIN='/usr/bin'

# Configure executables in bin
echo 'SETTING PERMISSIONS'
chmod +x                           $BIN_DIR/clueless
chmod -v 444                       $ETC_DIR/environment.ts.template

echo 'CREATING SYMBOLIC LINK IN /usr/bin'
ln    -sv     $BIN_DIR/clueless    $USR_BIN/clueless

echo 'GENERATING DEFAULT CONFIGURATION'
bash $BIN_DIR/setGlobalConfiguration.sh

##############################################################################
# Frontend Node installation
##############################################################################
cd $FRONTEND_DIR

echo "RUNNING npm uninstall * IN $FRONTEND_DIR"
npm uninstall *

echo "RUNNING npm install IN $FRONTEND_DIR"
npm install

##############################################################################
# Serverside Node installation
##############################################################################
cd $SERVERSIDE_DIR

echo "RUNNING npm uninstall * IN $SERVERSIDE_DIR"
npm uninstall *

echo "RUNNING npm install IN $SERVERSIDE_DIR"
npm install
