#!/bin/bash
##############################################################################
# File: postinst
# Author: Nate Lao (nlao1@jh.edu)
# Created On: 3/30/2020
# Description:
#       Debian post installation script.
##############################################################################

ANGULAR_DIR='/opt/clueless/src/frontend'
BIN_DIR='/opt/clueless/bin'
ETC_DIR='/opt/clueless/etc'
USR_BIN='/usr/bin'

# Configure executables in bin
echo 'SETTING PERMISSIONS'
chmod +x                           $BIN_DIR/clueless
chmod -v 444                       $ETC_DIR/environment.ts.template

echo 'CREATING SYMBOLIC LINK IN /usr/bin'
ln    -sv     $BIN_DIR/clueless    $USR_BIN/clueless

echo 'GENERATING CONFIGURATION'
bash $BIN_DIR/modifyConfig.sh

##############################################################################
# Angular installation
##############################################################################
cd $ANGULAR_DIR

echo 'RUNNING npm uninstall *'
npm uninstall *

echo 'RUNNING npm install'
npm install
