#!/bin/bash
##############################################################################
# File: prerm
# Author: Nate Lao (nlao1@jh.edu)
# Created On: 3/30/2020
# Description:
#       Debian pre removal script for Clueless.
##############################################################################

ANGULAR_DIR='/opt/clueless/src/frontend'

##############################################################################
# Kill any existing services
##############################################################################
echo "KILLING node"
killall node

echo "KILLING npm"
killall npm

echo "KILLING ng"
pkill -f ng

##############################################################################
# Angular removal
##############################################################################
cd $ANGULAR_DIR

echo 'RUNNING npm uninstall *'
npm uninstall *
